apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
 name: modern.xp-demo.crossplane.io
 labels:
   ux: modern
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: xp-demo.crossplane.io/v1alpha1
    kind: XLandingZone
  mode: Pipeline
  pipeline:
  - step: run-func
    functionRef:
      name: demo-xfn-claim-com
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Inputs
      ux: modern
  - step: ready
    functionRef:
      name: function-auto-ready
